### ISSUE TITLE
Package `mustache-0.22" is unavailable

### ISSUE THREAD

**Issue by nocLyt** [emacsorphanage/org-page#142]
一开始是 ht is unavailable 。

我去设置了 melpa 源 。

现在是出现 Package `mustache-0.22" is unavailable 这个错误

**Comment by standino** [comment]
谁能在国内建一个emacs的源啊？

**Comment by kelvinh** [comment]
However, mustache is in melpa: http://melpa.org/#/mustache. Could you please use `package-list-packages` command to see if mustache is in the list?

**Comment by nocLyt** [comment]
@kelvinh  Sorry, I can't see mustache in the list. 
But I have installed mustache from elpa.

![image](https://cloud.githubusercontent.com/assets/3166027/7532915/f79bee1c-f59e-11e4-884e-550294f734ec.png)

I think the version isn't right.
￼

![image](https://cloud.githubusercontent.com/assets/3166027/7532953/6333f296-f59f-11e4-8ff6-a1a08c66302a.png)

**Comment by kelvinh** [comment]
`mustache` and `mustache-mode` are two different packages. org-page depends on `mustache` but not `mustache-mode`.

**Comment by kelvinh** [comment]
Use `package-refresh-contents` to refresh the list, and also, check if you have the following configuration in your Emacs configuration file:

```
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
```

**Comment by vipzrx** [comment]
https://www.reddit.com/r/emacs/comments/2k2kmv/melpamilkboxnet_is_now_melpaorg/

现在改名了

国内不能访问，需要设置成 

ELPA 镜像 - Emacs China
http://elpa.emacs-china.org/

**Comment by kelvinh** [comment]
@vipzrx Thanks for the reminder!
