### ISSUE TITLE
org mode 下载两次

### ISSUE THREAD

**Issue by ZucchiniY** [emacsorphanage/org-page#225]
使用 `use-package` 加载 org 和 org-page 的时候。如果清空所有 elpa 内容，重新下载的时候，会重新下载一个 org 。

``` emacs-lisp
(use-package org :ensure org-plus-contrib)
(use-package org-page :ensure t)
```
这样启动emacs之后，会有两个org mode package在elpa下,一个是org,一个是org-plus-contrib。

<img width="211" alt="2018-02-07 15 06 17" src="https://user-images.githubusercontent.com/6075807/35903324-9bb1ec34-0c19-11e8-8426-aa398fae262e.png">

有没有办法，在加载包的时候，使用 org-plus-contrib 中的内容？

**Comment by kelvinh** [comment]
看起来org-plus-contrib是单独的一个包？

**Comment by yantar92** [comment]
`org-plus-contrib` is not longer a thing. Also, package management has nothing to do with org-page. Closing.
