### ISSUE TITLE
The new upstream doesn't exist anymore

### ISSUE THREAD

**Issue by tarsius** [emacsorphanage/org-page#233]
@shakthimaan The readme of this repository sais:

> Sorry folks, This project is not under active development any more. The new maintainer is here: https://gitlab.com/shakthimaan/org-page.

Unfortunately this newer gitlab repository of yours does not exist anymore. Could you tell us more about that? Did you move it elsewhere? Did you give up on it? Does someone else maintain it now?

**Comment by tarsius** [comment]
@sillykelvin If you moved on to some other org-based blogging utility, then what is it and why? Are there any issues with `org-page` or do you just don't want to / cannot maintain it anymore?

**Comment by shakthimaan** [comment]
I have not had much time to work on org-page. If you would like to maintain org-page, please feel free to work on it. Thanks!

**Comment by tarsius** [comment]
I just saw a nice looking blog and followed the "created with" link. I'm not really interested in maintaining this, at least not at this time and not before investing some time comparing with org-based alternatives.

But if I end up maintaining this package (or maybe must making some contributions), then I would like to base that on the latest code. As I understand it that would be your repository. But since you deleted the repository, that is not possible. Or maybe you didn't actually make any changes before abandoning that, but others cannot know that because you have unpublished your repository.

**Comment by shakthimaan** [comment]
> Or maybe you didn't actually make any changes 

Yes, I haven't made any changes to it. You can fork the repository from @sillykelvin.

**Comment by tarsius** [comment]
Okay, thanks for the information.

I guess it would be best if @sillykelvin could revert the changes to the readme that pointed at your short-lived repository, but since this package is now unmaintained, I could also understand if he didn't. Anyway, there's now this issue with additional information about the situation, which should help if I or someone else picked this up in the future.

**Comment by sillykelvin** [comment]
Broken link removed.

**Comment by sillykelvin** [comment]
> @sillykelvin If you moved on to some other org-based blogging utility, then what is it and why? Are there any issues with `org-page` or do you just don't want to / cannot maintain it anymore?

@tarsius Sorry, I'm just not interested in Emacs/Org-mode anymore, and don't have much time to continue to contribute to `org-page`. However, its current state is stable, it works well, at least works well for me in the past.

**Comment by tarsius** [comment]
@sillykelvin That's perfectly okay! Thanks for responding and taking the time to remove the link.

Above I wrote as a potentially interested user but I am also interested in this as the maintainer of the [Emacsmirror](https://emacsmirror.net) and specifically the [Emacsorphanage](https://github.com/emacsorphanage). The latter serves as a place where abandoned packages can receive limited maintenance and later hopefully be handed over to new maintainers.

One benefit of moving repositories under the control of that account is that it makes it easier to later transfer to someone else because the original author/maintainer does not have to get involved. Another is that you would no longer have to deal with threads like this, the maintainer of the orphanage (that's me) would take care of it instead. (You could remain subscribed to the issue tracker and chime in if/when you want to.)

If you would like to do this, then you would have to transfer the repository to me and I would then transfer it to the organization. (Directly is not possible because you are not a member of the organization.)

**Comment by sillykelvin** [comment]
Thanks for the advice, and it seems that's the best place for this repo! However, I have never transferred repos before, so: 1. What will happen to the repo in my account, will the links linked to this repo all be broken? 2. Will the issues/commits/PRs be kept? (The answer seems to be yes to Q2?)

**Comment by tarsius** [comment]
> 1. What will happen to the repo in my account, will the links linked to this repo all be broken?

Github puts redirects in place, so all existing links should be preserved. (This works for the web interface and `git`, but not the API.)

> 2. Will the issues/commits/PRs be kept? (The answer seems to be yes to Q2?)

Yes, this is correct.

**Comment by sillykelvin** [comment]
@tarsius Yeah, after the questions asked, I then found the answers in GitHub [docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository). I have sent a transfer request of this repo to your personal account.

**Comment by tarsius** [comment]
Argl... I waited too long and now the transfer request has expired. Please initiate it again. (It's really silly that they don't show a notification here in the web interface and that they let these requests time out after approximately 24h.)

**Comment by sillykelvin** [comment]
@tarsius Another request is sent.

**Comment by tarsius** [comment]
Thanks! I saw it in time this time around.
