### ISSUE TITLE
Source Code Hightlighting

### ISSUE THREAD

**Issue by sillykelvin** [emacsorphanage/org-page#88]
Org-export uses `htmlize.el` to hightlight code blocks, as it depends on Emacs' theme, so it is a little annoying: if the theme changes, all color will change, and those files contain source code blocks will change, and a `git commit` is needed, though there is **no actual useful content change!**

Consider using google [prettify.js](https://code.google.com/p/google-code-prettify/) instead.

**Comment by kelvinh** [comment]
Now there is an variable to control this behavior: `op/highlight-render`, thanks to @CodeFalling's contribution!
