### ISSUE TITLE
Date and tags after post title, not in footer

### ISSUE THREAD

**Issue by kit1980** [emacsorphanage/org-page#92]
In my custom theme I copied code for date and tags from footer.mustache to post.mustache (I've also tried header and nav template just to test) - and the code works in footer.mustache only. I think it's because {{date}} and {{tag-links}} are empty for other templates.

Is it possible to make custom theme to show date and tags after post title, not it footer?

**Comment by shackra** [comment]
a very generic solution, so any sort of variables can be use on any custom/standard mustache template.

I wonder if it is possible to define any variable in org as `#+CUSTOM_VARIABLE`, I could use certain custom variables to modify the template and/or add extra information to the generated posts, i.e.: setting a variable as `#+COVER_IMG: https://i.imgur.com/example.png` and then using `{{cover_img}}` as `<meta property="og:image" content="{{cover_img}}" />` on `header.mustache` template, setting your posts ready for social media!

**Comment by kelvinh** [comment]
Yeah, I will do some evaluations on this, thanks for the advice!

**Comment by Linuus** [comment]
Yes! This would be awesome! :+1:
